config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  resources :keys
  resources :peers
  resources :psks

  resources :interfaces do
    resources :peers
  end

  get '/interfaces/:id/qr', to: 'interfaces#show_qr', as: 'show_qr'
  get '/interfaces/:id/show', to: 'interfaces#show_config', as: 'show_config'
  get '/interfaces/:id/file', to: 'interfaces#download_config', as: 'download_config'

  get '/network', to: 'graph#show', as: 'graph'
  get '/network2', to: 'graph#show2', as: 'graph2'
  get '/network/json', to: 'graph#json', as: 'graph_json'

  resources :hosts

  get '/hosts/:id/upload', to: 'hosts#upload', as: 'upload_wizard'
  patch '/hosts/:id/upload', to: 'hosts#upload'

  match '*path' => 'application#home', via: [:get, :post]

end

app/models/host.rb
class Host < ApplicationRecord
  validates :name, presence: true
  validates :username, presence: true
  validates :hostname, presence: true
  validates :port, presence: true, length: { minimum: 0, maximum: 65_353 }
  validates :path, presence: true

  before_validation :default_values

  paginates_per 10

  private

  def default_values
    self.port ||= 22
    self.path ||= '/etc/wireguard'
  end

end

app/controllers/hosts_controller.rb
require 'net/sftp'

class HostsController < ApplicationController
  before_action :set_host, only: %i[ show edit update destroy upload ]

  # GET /hosts or /hosts.json
  def index
    @hosts = Host.all.order('name').page params[:page]
  end

  # GET /hosts/1 or /hosts/1.json
  def show
  end

  # GET or PATCH /hosts/1/upload
  def upload
    unless params[:host].nil?
      @host.errors.add(:id, 'not selected') if params[:host][:id].nil?
      @host.errors.add(:interface_id, 'not selected') if params[:host][:interface_id] == ''
    end
    if params[:host].nil? || @host.errors.any?
      @hosts = Host.all
      @interfaces = Interface.all
      render :upload
    else
      interface = Interface.find(params[:host][:interface_id])
      filename = File.join(@host.path, "#{interface.name}.conf")
      config_file = interface.config_file
      overwrite = params[:host][:overwrite] == '1' ? true : false
      sftp_upload_file(filename, config_file, @host.hostname, @host.username, overwrite)
      redirect_to hosts_url, {
        notice: "Uploading configuration file (#{interface.name}.conf) to #{@host.name}..."
      }
    end
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts or /hosts.json
  def create
    @host = Host.new(host_params)
    respond_to do |format|
      if @host.save
        format.html { redirect_to hosts_url, notice: "Host was successfully created." }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1 or /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to hosts_url, notice: "Host was successfully updated." }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1 or /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: "Host was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def host_params
      params.require(:host).permit(:name, :username, :hostname, :port, :path, :key)
    end

    # Upload file using SFTP.
    def sftp_upload_file(filename, data, hostname, username, overwrite = false)
      Net::SFTP.start(hostname, username) do |sftp|
         sftp.stat(filename) do |response|
           if !response.ok? || overwrite
             sftp.upload! StringIO.new(data), filename
           end
         end
      end
    end

end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<% if notice %>
<div class="notification">
  <%= notice %>
</div>
<% end %>

<%= form_with(model: host) do |form| %>
  <% if host.errors.any? %>
    <div class="notification is-danger">
      <b><%= pluralize(host.errors.count, "error") %> prohibited this host from being saved:</b>
      <ul>
        <% host.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: 'label' %>
    <div class="control">
      <%= form.text_field :name, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :hostname, 'Hostname or IP address', class: 'label' %>
    <div class="control">
      <%= form.text_field :hostname, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :port, 'SSH port (default = 22)', class: 'label' %>
    <div class="control">
      <%= form.number_field :port, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :username, 'Username', class: 'label' %>
    <div class="control">
      <%= form.text_field :username, class: 'input' %>
    </div>
  </div>

<!--  <div class="field">
    <%= form.label :key, 'Key (optional)', class: 'label' %>
    <div class="control">
      <%= form.text_field :key, class: 'input' %>
    </div>
  </div> -->

  <div class="field">
    <%= form.label :path, 'Remote path (default = /etc/wireguard)', class: 'label' %>
    <div class="control">
      <%= form.text_field :path, class: 'input' %>
    </div>
  </div>

  <br />

  <div class="actions">
    <%= form.submit class: 'button is-primary' %>
  </div>

<% end %>

app/views/hosts/edit.html.erb
<h1 class="title">Editing Host</h1>

<%= render 'form', host: @host %>

<br />

<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<h1 class="title">Hosts</h1>

<h2 class="subtitle">
  <%= pluralize(@hosts.total_count, 'host') %> found
</h2>

<% if notice %>
<div class="notification">
  <%= notice %>
</div>
<% end %>

<%= paginate @hosts %>

<table class="table is-hoverable is-fullwidth is-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th nowrap>Hostname or IP address</th>
      <th>Port</th>
      <th>Username</th>
      <th>Remote path</th>
      <th nowrap>Last updated</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td nowrap><b><%= link_to (fa_icon 'database') + " #{host.name}", edit_host_path(host) %></b></td>
        <td nowrap><%= link_to (fa_icon 'external-link') + " #{host.hostname}", "ssh://#{host.username}@#{host.hostname}:#{host.port}", title: 'Open in terminal' %></td>
        <td nowrap><%= host.port %></td>
        <td nowrap><%= host.username %></td>
        <td><code><%= host.path %></code></td>
        <td nowrap><%= l host.updated_at, format: :default %></td>
        <td nowrap><%= link_to (fa_icon 'upload') + ' Upload', upload_wizard_path(host) %></td>
        <td nowrap><%= link_to (fa_icon 'edit') + ' Edit', edit_host_path(host) %></td>
        <td nowrap><%= link_to (fa_icon 'trash') + ' Remove', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Host', new_host_path, class: 'button' %>

app/views/hosts/new.html.erb
<h1 class="title">New Host</h1>

<%= render 'form', host: @host %>

<br />

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @host.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @host.username %>
</p>

<p>
  <strong>Hostname:</strong>
  <%= @host.hostname %>
</p>

<p>
  <strong>Port:</strong>
  <%= @host.port %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/upload.html.erb
<h1 class="title">Upload configuration file</h1>

<% if notice %>
<div class="notification">
  <%= notice %>
</div>
<% end %>

<%= form_with(model: @host, url: upload_wizard_path(@host)) do |form| %>
  <% if @host.errors.any? %>
    <div class="notification is-danger">
      <b><%= pluralize(@host.errors.count, "error") %> prohibited the configuration file from being uploaded:</b>
      <ul>
        <% @host.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id, 'Destination host', class: 'label' %>
    <div class="control has-icons-left">
      <span class="select">
        <%= form.collection_select :id, @hosts, :id, :hostname, class: 'input', include_blank: 'Select a host' %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-database"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <%= form.label :interface_id, 'Interface / Configuration file', class: 'label' %>
    <div class="control has-icons-left">
      <span class="select">
        <%= form.collection_select :interface_id, @interfaces, :id, :pretty_name, class: 'input', include_blank: 'Select an interface' %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-server"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <%= form.label :overwrite, 'File handling', class: 'label' %>
    <%= form.check_box :overwrite %> Overwrite file if already exists?
  </div>

  <hr />

  <div class="notification is-warning">
    <b>Warning</b> &mdash; With great power comes great responsibility. Please use the upload function at at your own risk.
  </div>

  <hr />

  <div class="actions">
    <%= form.submit 'Upload', class: 'button is-primary', data: { confirm: 'Are you sure?' } %>
  </div>

  <br />

<% end %>

<%= link_to 'Back', hosts_path %>