config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  resources :keys
  resources :peers
  resources :psks

  resources :interfaces do
    resources :peers
  end

  get '/interfaces/:id/qr', to: 'interfaces#show_qr', as: 'show_qr'
  get '/interfaces/:id/show', to: 'interfaces#show_config', as: 'show_config'
  get '/interfaces/:id/file', to: 'interfaces#download_config', as: 'download_config'

  get '/network', to: 'graph#show', as: 'graph'
  get '/network2', to: 'graph#show2', as: 'graph2'
  get '/network/json', to: 'graph#json', as: 'graph_json'

  resources :hosts

  get '/hosts/:id/upload', to: 'hosts#upload', as: 'upload_wizard'
  patch '/hosts/:id/upload', to: 'hosts#upload'

  match '*path' => 'application#home', via: [:get, :post]

end

app/models/interface.rb
class Interface < ApplicationRecord
  belongs_to :key
  belongs_to :psk, optional: true
  has_many :peers, dependent: :destroy

  validates :name, presence: true
  validates :key, presence: true
  validates :address, presence: true
  validates :port, presence: false, length: { minimum: 0, maximum: 65_353 }, allow_blank: true

  # before_validation :default_values
  # after_save :auto_assign_psk

  paginates_per 10

  def pretty_name
    "#{key.name} | #{name}.conf — #{key.privatekey}"
  end

  def config_file
    <<~CONFIG
    # Config file generated at #{Time.now}\n
    #{config_interface}
    #{config_peers}
    CONFIG
  end

  def config_interface
    str = "[Interface]\n"
    str << "# #{key.name}\n"
    str << "PrivateKey = #{key.privatekey}\n"
    str << "Address = #{address}\n"
    str << "PostUp = #{postup}\n" if postup?
    str << "PostDown = #{postdown}\n" if postdown?
    str << "ListenPort = #{port}\n" if port?
    str << "DNS = #{dns}\n" if dns?
    str
  end

  def config_peers
    str = ''
    peers.each do |peer|
      str << "[Peer]\n"
      str << "# #{peer.key.name}\n"
      str << "PublicKey = #{peer.key.publickey}\n"
      str << "PresharedKey = #{peer.psk.psk}\n" unless peer.psk.nil?
      str << "AllowedIPs = #{peer.allowed_ips}\n" if peer.allowed_ips?
      str << "Endpoint = #{peer.endpoint}\n" if peer.endpoint?
      str << "PersistentKeepalive = #{peer.keepalive}\n" if peer.keepalive?
      str << "\n"
    end
    str
  end

  private

  def default_values
    self.port ||= 51_820
  end

  # def auto_assign_psk
  #   peers.each do |peer|
  #     peer.psk_id = psk_id
  #     peer.save
  #   end
  # end

end

app/controllers/interfaces_controller.rb
require 'rqrcode'

class InterfacesController < ApplicationController
  include QrHelper
  include PeersHelper

  before_action :set_interface, only: %i[
    show edit update destroy show_qr show_config download_config
  ]

  # GET /interfaces or /interfaces.json
  def index
    @interfaces = Interface.all.includes(:key).order('keys.name').page params[:page]
  end

  # GET /interfaces/1 or /interfaces/1.json
  def show
  end

  # GET /interfaces/new
  def new
    @interface = Interface.new
  end

  # GET /interfaces/1/edit
  def edit
  end

  # GET /interfaces/1/qr
  def show_qr
    send_data create_qr_as_png(@interface.config_file), type: 'image/png', disposition: 'inline'
  end

  # GET /interfaces/1/show
  def show_config
    render plain: @interface.config_file
  end

  # GET /interfaces/1/file
  def download_config
    send_data @interface.config_file, filename: "#{@interface.name}.conf"
  end

  # POST /interfaces or /interfaces.json
  def create
    @interface = Interface.new(interface_params)

    respond_to do |format|
      if @interface.save
        format.html { redirect_to interfaces_url, notice: "Interface was successfully created." }
        format.json { render :show, status: :created, location: @interface }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interfaces/1 or /interfaces/1.json
  def update
    respond_to do |format|
      if @interface.update(interface_params)
        format.html { redirect_to interfaces_url, notice: "Interface was successfully updated." }
        format.json { render :show, status: :ok, location: @interface }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interfaces/1 or /interfaces/1.json
  def destroy
    @interface.destroy
    respond_to do |format|
      format.html { redirect_to interfaces_url, notice: "Interface was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interface
      @interface = Interface.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def interface_params
      params.require(:interface).permit(:name, :address, :psk_id, :dns, :key_id, :postup, :postdown, :port)
    end

end

app/helpers/interfaces_helper.rb
require 'rouge'

module InterfacesHelper

  def highlight_syntax(str)
    lexer = Rouge::Lexers::Conf.new
    formatter = Rouge::Formatters::HTMLInline.new('github')
    formatter.format(lexer.lex(str)).strip.html_safe
  end

end

app/views/interfaces/_form.html.erb
<% if notice %>
<div class="notification">
  <%= notice %>
</div>
<% end %>

<%= form_with(model: interface) do |form| %>
  <% if interface.errors.any? %>
    <div class="notification is-danger">
      <b><%= pluralize(interface.errors.count, "error") %> prohibited this interface from being saved:</b>
      <ul>
        <% interface.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :key, 'Interface / Private key', class: 'label' %>
    <p class="control has-icons-left">
      <span class="select">
        <%= form.collection_select :key_id, Key.all, :id, :pretty_privatekey, include_blank: 'Select a key' %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-server"></i>
      </span>
    </p>
  </div>

  <div class="field">
    <%= form.label :name, 'Configuration file', class: 'label' %>
    <div class="field has-addons">
      <div class="control">
        <%= form.text_field :name, class: 'input' %>
      </div>
      <div class="control">
        <a class="button is-static">.conf</a>
      </div>
    </div>
  </div>

  <!-- <div class="field">
    <%= form.label :psk, 'Pre-shared key (optional)', class: 'label' %>
    <p class="control has-icons-left">
      <span class="select">
      <%= form.collection_select :psk_id, Psk.all, :id, :pretty_name, include_blank: 'Select a key' %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-shield"></i>
      </span>
    </p>
  </div> -->

  <div class="field">
    <%= form.label :address, class: 'label' %>
    <div class="control">
      <%= form.text_field :address, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :dns, 'DNS servers', class: 'label' %>
    <div class="control">
      <%= form.text_field :dns, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :port, 'Listening port (default = 51280)', class: 'label' %>
    <div class="control">
      <%= form.number_field :port, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :postup, 'PostUp command', class: 'label' %>
    <div class="control">
      <%= form.text_area :postup, class: 'textarea', rows: 1 %>
    </div>
  </div>

  <div class="field">
    <%= form.label :postdown, 'PostDown command', class: 'label' %>
    <div class="control">
      <%= form.text_area :postdown, class: 'textarea', rows: 1 %>
    </div>
  </div>

  <div class="control">
    <%= form.submit class: 'button is-primary' %>
  </div>

<% end %>

app/views/interfaces/edit.html.erb
<div class="columns">

  <div class="column is-7">
    <h1 class="title">Editing Interface</h1>
    <%= render 'form', interface: @interface %>
  </div>

  <div class="column is-1"></div>

  <div class="column is-4">
    <h1 class="title">Peerings</h1>
    <% if @interface.peers.size > 0 %>
    <div class="notification">
      <b>This interface is currently configured with <%= pluralize(@interface.peers.size, 'peer') %>.</b>
    </div>
      <%= render partial: 'partials/peers_table', locals: { peers: @interface.peers.order('allowed_ips') } %>
    <% else %>
    <div class="notification">
      You currently have not configured any peers for this interface.
    </div>
    <% end %>
  </div>

</div>

<br />

<%= link_to 'Back', interfaces_path %>

app/views/interfaces/index.html.erb
<h1 class="title">WireGuard interfaces</h1>

<h2 class="subtitle">
  <%= pluralize(@interfaces.total_count, 'interface') %> found
</h2>

<% if notice %>
<div class="notification">
  <%= notice %>
</div>
<% end %>

<%= paginate @interfaces %>

<table class="table is-hoverable is-fullwidth is-striped">
  <thead>
    <tr>
      <th>Interface</th>
      <th>Preview</th>
      <th nowrap># of peers</th>
      <th>Peers</th>
      <th>Address</th>
      <th>Port</th>
      <th colspan="2">Configuration file</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @interfaces.each do |interface| %>
      <tr>
        <td nowrap><%= render partial: 'partials/interface_name', locals: { interface: interface } %></td>
        <td nowrap><%= render partial: 'partials/interface_config', locals: { interface: interface } %></td>
        <td nowrap><%= link_to (fa_icon 'user') + " #{pluralize(interface.peers.size, 'peer')}", interface_peers_path(interface.id) %></td>
        <td nowrap><%= render partial: 'partials/peers_status', locals: { interface: interface, peers: interface.peers } %></td>
        <td><%= interface.address %></td>
        <td><%= interface.port? ? interface.port : '-' %></td>
        <td nowrap><%= link_to (fa_icon 'download') + " Download", download_config_path(interface) %></td>
        <td nowrap><%= link_to (fa_icon 'qrcode') + ' QR', show_qr_path(interface), target: '_blank' %></td>
        <td nowrap><%= link_to (fa_icon 'edit') + ' Edit', edit_interface_path(interface) %></td>
        <td nowrap><%= link_to (fa_icon 'trash') + ' Remove', interface, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Interface', new_interface_path, class: 'button' %>

<script>
  let cjs = new ClipboardJS('.copy');

  document.querySelectorAll('.modal-button').forEach(function(el) {
    el.addEventListener('click', function() {
      var target = document.querySelector(el.getAttribute('data-target'));
      target.classList.add('is-active');
      target.querySelectorAll('.close').forEach(function(t) {
        t.addEventListener('click',   function() {
          target.classList.remove('is-active');
        });
      });
    });
    el.addEventListener('keydown', function(e) {
      var code = e.keyCode || e.which;
      if (code == 27) {
        var target = document.querySelector(el.getAttribute('data-target'));
        target.classList.remove('is-active');
      }
    });
  });
</script>

app/views/interfaces/new.html.erb
<h1 class="title">New Interface</h1>

<%= render 'form', interface: @interface %>

<br />

<%= link_to 'Back', interfaces_path %>

app/views/interfaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @interface.name %>
</p>

<p>
  <strong>Key:</strong>
  <%= @interface.key.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @interface.address %>
</p>

<p>
  <strong>DNS:</strong>
  <%= @interface.dns %>
</p>

<p>
  <strong>PostUp:</strong>
  <%= @interface.postup %>
</p>

<p>
  <strong>PostDown:</strong>
  <%= @interface.postdown %>
</p>

<p>
  <strong>ListenPort:</strong>
  <%= @interface.port %>
</p>

<%= link_to 'Edit', edit_interface_path(@interface) %> |
<%= link_to 'Back', interfaces_path %>