config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  resources :keys
  resources :peers
  resources :psks

  resources :interfaces do
    resources :peers
  end

  get '/interfaces/:id/qr', to: 'interfaces#show_qr', as: 'show_qr'
  get '/interfaces/:id/show', to: 'interfaces#show_config', as: 'show_config'
  get '/interfaces/:id/file', to: 'interfaces#download_config', as: 'download_config'

  get '/network', to: 'graph#show', as: 'graph'
  get '/network2', to: 'graph#show2', as: 'graph2'
  get '/network/json', to: 'graph#json', as: 'graph_json'

  resources :hosts

  get '/hosts/:id/upload', to: 'hosts#upload', as: 'upload_wizard'
  patch '/hosts/:id/upload', to: 'hosts#upload'

  match '*path' => 'application#home', via: [:get, :post]

end

app/models/peer.rb
class Peer < ApplicationRecord
  include PeersHelper

  belongs_to :key
  belongs_to :interface
  belongs_to :psk, optional: true

  validates :key, presence: true
  validates :interface, presence: true
  validates :psk, presence: false
  validates :allowed_ips, presence: false
  validates :endpoint, presence: false

  after_save :auto_assign_psk

  paginates_per 15

  private

  def auto_assign_psk
    reciprocal = reciprocal_peer(self)
    unless reciprocal.nil?
      reciprocal.update_columns(psk_id: psk_id)
    end
  end

end

app/controllers/peers_controller.rb
class PeersController < ApplicationController
  before_action :set_peer, only: %i[ show edit update destroy ]

  # GET /peers or /peers.json
  def index
    @peers = Peer.all.includes(:key).includes(interface: [:key]).order('keys.name').order('interfaces.name')
    if params[:interface_id]
      @peers = @peers.where(interface_id: params[:interface_id])
    end
    @peers = @peers.page params[:page]
  end

  # GET /peers/1 or /peers/1.json
  def show
  end

  # GET /peers/new
  def new
    @peer = Peer.new
  end

  # GET /peers/1/edit
  def edit
  end

  # POST /peers or /peers.json
  def create
    @peer = Peer.new(peer_params)
    respond_to do |format|
      if @peer.save
        format.html { redirect_to peers_url, notice: "Peer was successfully created." }
        format.json { render :show, status: :created, location: @peer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @peer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peers/1 or /peers/1.json
  def update
    respond_to do |format|
      if @peer.update(peer_params)
        format.html { redirect_to peers_url, notice: "Peer was successfully updated." }
        format.json { render :show, status: :ok, location: @peer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @peer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peers/1 or /peers/1.json
  def destroy
    @peer.destroy
    respond_to do |format|
      format.html { redirect_to peers_url, notice: "Peer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peer
      @peer = Peer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def peer_params
      params.require(:peer).permit(:description, :allowed_ips, :endpoint, :psk_id, :key_id, :interface_id, :keepalive)
    end
end

app/helpers/peers_helper.rb
module PeersHelper

  def valid_peering?(peer)
    !reciprocal_peer(peer).nil?
  end

  def reciprocal_peer(peer)
    Peer.where(key: peer.interface.key).find_by(interface_id: peer.key.interfaces.ids)
  end

end

app/views/peers/_form.html.erb
<% if notice %>
<div class="notification">
  <%= notice %>
</div>
<% end %>

<%= form_with(model: peer) do |form| %>
  <% if peer.errors.any? %>
    <div class="notification is-danger">
      <b><%= pluralize(peer.errors.count, "error") %> prohibited this peer from being saved:</b>
      <ul>
        <% peer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :key, 'Peer / Public key', class: 'label' %>
    <p class="control has-icons-left">
      <span class="select">
        <%= form.collection_select :key_id, Key.all, :id, :pretty_publickey, class: 'input', include_blank: 'Select a key' %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-key"></i>
      </span>
    </p>
  </div>

  <div class="field">
    <%= form.label :interface, 'Interface / Private key', class: 'label' %>
    <p class="control has-icons-left">
      <span class="select">
        <%= form.collection_select :interface_id, Interface.all, :id, :pretty_name, class: 'input', include_blank: 'Select an interface' %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-server"></i>
      </span>
    </p>
  </div>

  <div class="field">
    <%= form.label :psk_id, 'Pre-shared key (optional)', class: 'label' %>
    <p class="control has-icons-left">
      <span class="select">
        <%= form.collection_select :psk_id, Psk.all, :id, :pretty_name, class: 'input', include_blank: 'Select a key' %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-shield"></i>
      </span>
    </p>
  </div>

  <div class="field">
    <%= form.label :allowed_ips, 'Allowed IPs', class: 'label' %>
    <div class="control">
      <%= form.text_field :allowed_ips, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :endpoint, 'Endpoint', class: 'label' %>
    <div class="control">
      <%= form.text_field :endpoint, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :keepalive, 'Persistent keepalive', class: 'label' %>
    <div class="field has-addons">
      <div class="control">
        <%= form.number_field :keepalive, class: 'input' %>
      </div>
      <div class="control">
        <a class="button is-static">ms</a>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, class: 'label' %>
    <div class="control">
      <%= form.text_area :description, class: 'textarea', rows: 2 %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/peers/edit.html.erb
<h1 class="title">Editing Peer</h1>

<%= render 'form', peer: @peer %>

<br />

<%= link_to 'Back', (['', '/peers'].include? relative_path(request.referer)) ? peers_path : interfaces_path %>

app/views/peers/index.html.erb
<h1 class="title">WireGuard peerings</h1>

<h2 class="subtitle">
  <%= pluralize(@peers.total_count, 'peer') %> found
  <% if !params[:interface_id].nil? && @peers.size > 0 %>
  configured on interface <b><%= link_to @peers.first.interface.key.name, edit_interface_path(@peers.first.interface) %></b>
  <% end %>
</h2>

<% if notice %>
<div class="notification">
  <%= notice %>
</div>
<% end %>

<%= paginate @peers %>

<table class="table is-hoverable is-fullwidth is-striped">
  <thead>
    <tr>
      <th>Peer</th>
      <th>Interface</th>
      <th colspan="2">Peering</th>
      <th nowrap>Allowed IPs</th>
      <th>Endpoint</th>
      <th>Keepalive</th>
      <th nowrap>Pre-shared key</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @peers.each do |peer| %>
      <tr>
        <td nowrap>
          <b><%= link_to (fa_icon 'user') + " #{peer.key.name}", edit_peer_path(peer), title: "Public key: #{peer.key.short_publickey}" %></b>
        </td>
        <td nowrap><%= render partial: 'partials/interface_name', locals: { interface: peer.interface } %></td>
        <td nowrap><%= render partial: 'partials/peer_status', locals: { peer: peer } %></td>
        <td nowrap>
          <% if valid_peering?(peer) %>
          <%= link_to (fa_icon 'gg') + ' Counterparts', interface_peers_path(reciprocal_peer(peer).interface) %></td>
          <% else %>
          -
          <% end %>
        <td><%= peer.allowed_ips? ? "#{peer.allowed_ips}" : '-' %></td>
        <td nowrap><%= peer.endpoint? ? "#{peer.endpoint}" : '-' %></td>
        <td nowrap><%= peer.keepalive? ? "#{peer.keepalive} ms" : '-' %></td>
        <td nowrap>
          <% if peer.psk_id? %>
          <b><%= link_to (fa_icon 'shield') + " #{peer.psk.name}", edit_psk_path(peer.psk), title: "Pre-shared key: #{peer.psk.short_psk}" %></b>
          <% else %>
          -
          <% end %>
        </td>
        <td nowrap><%= link_to (fa_icon 'edit') + ' Edit', edit_peer_path(peer) %></td>
        <td nowrap><%= link_to (fa_icon 'trash') + ' Remove', peer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Peer', new_peer_path, class: 'button' %>

app/views/peers/new.html.erb
<h1 class="title">New Peer</h1>

<%= render 'form', peer: @peer %>

<br />

<%= link_to 'Back', peers_path %>

app/views/peers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @peer.description %>
</p>

<p>
  <strong>Interface:</strong>
  <%= @peer.interface %>
</p>

<p>
  <strong>Allowed IPs:</strong>
  <%= @peer.allowed_ips %>
</p>

<p>
  <strong>Endpoint:</strong>
  <%= @peer.endpoint %>
</p>

<%= link_to 'Edit', edit_peer_path(@peer) %> |
<%= link_to 'Back', peers_path %>