config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  resources :keys
  resources :peers
  resources :psks

  resources :interfaces do
    resources :peers
  end

  get '/interfaces/:id/qr', to: 'interfaces#show_qr', as: 'show_qr'
  get '/interfaces/:id/show', to: 'interfaces#show_config', as: 'show_config'
  get '/interfaces/:id/file', to: 'interfaces#download_config', as: 'download_config'

  get '/network', to: 'graph#show', as: 'graph'
  get '/network2', to: 'graph#show2', as: 'graph2'
  get '/network/json', to: 'graph#json', as: 'graph_json'

  resources :hosts

  get '/hosts/:id/upload', to: 'hosts#upload', as: 'upload_wizard'
  patch '/hosts/:id/upload', to: 'hosts#upload'

  match '*path' => 'application#home', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyWire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/clipboard@2.0.8/dist/clipboard.min.js' %>
  </head>
  <body>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to image_tag('logo_transparent.png', width: 200, height: 40), root_url %>
      </div>

      <div id="navbarBasic" class="navbar-brand">
        <div class="navbar-start">
          <%= link_to (fa_icon 'home') + '&nbsp; Home'.html_safe, root_url, class: 'navbar-item' %>
          <%= link_to (fa_icon 'globe') + '&nbsp; Network'.html_safe, graph_path, class: 'navbar-item', 'data-turbolinks': false %>
          <%= link_to (fa_icon 'server') + '&nbsp; Interfaces'.html_safe, interfaces_path, class: 'navbar-item' %>
          <%= link_to (fa_icon 'user') + '&nbsp; Peerings'.html_safe, peers_path, class: 'navbar-item' %>
          <%= link_to (fa_icon 'key') + '&nbsp; Keys'.html_safe, keys_path, class: 'navbar-item' %>
          <%= link_to (fa_icon 'shield') + '&nbsp; PSKs'.html_safe, psks_path, class: 'navbar-item' %>
          <%= link_to (fa_icon 'database') + '&nbsp; Hosts'.html_safe, hosts_path, class: 'navbar-item' %>

          <!-- <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>
            <div class="navbar-dropdown">
              <a class="navbar-item">
                About
              </a>
              <a class="navbar-item">
                Contact
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item">
                Report an issue
              </a>
            </div>
          </div> -->
        </div>

        <!-- <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary">
                <strong>Sign up</strong>
              </a>
              <a class="button is-light">
                Log in
              </a>
            </div>
          </div>
        </div>-->
      </div>
    </nav>

    <section class="section">
      <div class="container is-fluid">
        <%= yield %>
      </div>
    </section>

  </body>
</html>

app/views/layouts/home.html.erb
<h1 class="title">Welcome to RubyWire!</h1>

<h2 class="subtitle">Manage your WireGuard hosts and servers smoothly</h2>

<div class="content">

  <p>
    This app provides a simple web interface for managing <b><a href="https://www.wireguard.com" target="_blank">WireGuard</a></b> keys and configuration files. It generates configuration files, create QR codes for your mobile devices or uploads configuration files directly to your hosts and servers.
  </p>

  <ul>
    <li>Generate and manage key pairs</li>
    <li>Generate and manage pre-shared keys</li>
    <li>Create and edit interface configuration</li>
    <li>Create and edit peer configuration</li>
    <li>Create and edit interface and peer associations</li>
    <li>Generate QR codes of your configuration files</li>
    <li>Upload configuration files to hosts and servers using <b><a href="https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol" target="_blank">SFTP</a></b></li>
  </ul>

  <p>The project is powered by <%= wg_version %>, Rails <%= Rails.version %> and Ruby <%= RUBY_VERSION %>.</p>

  <hr />

  <% if !wg? %>
  <div class="notification is-danger is-light">
    Please consider installing WireGuard on your system first. Read the installation instructions <a href="https://www.wireguard.com/install/">here</a>.
  </div>
  <% end %>

</div>